from botmoduleproject1.contracts.v1.execution import ExecutionLifecycleState as S

TRANSITIONS: dict[S, frozenset[S]] = {
    S.INTENT_CREATED: frozenset({S.VALIDATED, S.BLOCKED, S.REJECTED}),
    S.VALIDATED: frozenset({S.QUEUED, S.BLOCKED, S.FROZEN, S.REJECTED}),
    S.QUEUED: frozenset({S.SUBMITTED, S.BLOCKED, S.FROZEN, S.REJECTED, S.CANCEL_REQUESTED}),
    S.SUBMITTED: frozenset({S.ACKNOWLEDGED, S.REJECTED, S.BLOCKED, S.RECONCILIATION_PENDING}),
    S.ACKNOWLEDGED: frozenset(
        {S.PARTIALLY_FILLED, S.FILLED, S.CANCEL_REQUESTED, S.MODIFY_REQUESTED, S.EXPIRED, S.FROZEN}
    ),
    S.PARTIALLY_FILLED: frozenset(
        {S.PARTIALLY_FILLED, S.FILLED, S.CANCEL_REQUESTED, S.EXPIRED}
    ),
    S.FILLED: frozenset({S.RECONCILIATION_PENDING, S.RECONCILED}),
    S.CANCEL_REQUESTED: frozenset({S.CANCELLED, S.ACKNOWLEDGED, S.REJECTED}),
    S.CANCELLED: frozenset({S.RECONCILIATION_PENDING, S.RECONCILED}),
    S.MODIFY_REQUESTED: frozenset({S.MODIFIED, S.ACKNOWLEDGED, S.REJECTED}),
    S.MODIFIED: frozenset({S.ACKNOWLEDGED, S.QUEUED}),
    S.REJECTED: frozenset(),
    S.EXPIRED: frozenset({S.RECONCILIATION_PENDING}),
    S.BLOCKED: frozenset({S.FROZEN, S.REJECTED, S.QUEUED, S.RECOVERY_PENDING}),
    S.FROZEN: frozenset({S.RECOVERY_PENDING, S.REJECTED}),
    S.RECONCILIATION_PENDING: frozenset({S.RECONCILED, S.MISMATCH_DETECTED}),
    S.RECONCILED: frozenset(),
    S.MISMATCH_DETECTED: frozenset({S.RECOVERY_PENDING, S.FROZEN}),
    S.RECOVERY_PENDING: frozenset({S.RECOVERED, S.FROZEN}),
    S.RECOVERED: frozenset({S.QUEUED, S.BLOCKED}),
}

TERMINAL = frozenset({S.REJECTED, S.RECONCILED})


def can_transition(current: S, target: S) -> bool:
    return target in TRANSITIONS.get(current, frozenset())
