"""PostgreSQL DDL for PM8 Persistence.

Schema version catalog stays v1 (Seq 09) / v2 (Seq 10). This file is the
PostgreSQL dialect of those families plus NUMERIC, TIMESTAMPTZ, JSONB,
append-only triggers, unique idempotency, and SKIP LOCKED indexes.

Partitioning is documented, not enabled by default: RANGE(occurred_at) on
append-only high-volume tables (events, audit_log, outbox history) once
volume justifies it. Tests use unpartitioned tables so TRUNCATE stays simple.
"""

from __future__ import annotations

SCHEMA_PG_V1 = r"""
CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    checksum TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL,
    direction TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    sequence_no BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL UNIQUE,
    correlation_id TEXT NOT NULL,
    causation_id TEXT,
    idempotency_key TEXT,
    occurred_at TIMESTAMPTZ NOT NULL,
    event_type TEXT NOT NULL,
    producer TEXT NOT NULL,
    family TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    prev_hash TEXT NOT NULL,
    row_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS signals (
    signal_id TEXT PRIMARY KEY,
    event_id TEXT NOT NULL,
    symbol TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    committed_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
    order_id TEXT PRIMARY KEY,
    client_order_id TEXT NOT NULL UNIQUE,
    intent_id TEXT,
    verdict_id TEXT,
    state TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    committed_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS executions (
    execution_id TEXT PRIMARY KEY,
    order_id TEXT NOT NULL,
    venue_kind TEXT NOT NULL,
    venue_ticket TEXT,
    venue_callback_id TEXT,
    payload_json JSONB NOT NULL,
    committed_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS positions_proj (
    symbol TEXT PRIMARY KEY,
    qty NUMERIC(28, 8) NOT NULL,
    avg_px NUMERIC(28, 8) NOT NULL,
    as_of TIMESTAMPTZ NOT NULL,
    source_seq BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS idempotency_keys (
    edge TEXT NOT NULL,
    scope TEXT NOT NULL,
    key TEXT NOT NULL,
    result_ref TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    request_hash TEXT,
    PRIMARY KEY (edge, scope, key)
);

CREATE TABLE IF NOT EXISTS outbox (
    outbox_id TEXT PRIMARY KEY,
    event_id TEXT NOT NULL,
    topic TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    state TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,
    aggregate_id TEXT,
    correlation_id TEXT,
    causation_id TEXT,
    payload_version TEXT,
    claimed_by TEXT,
    claimed_until TIMESTAMPTZ,
    next_attempt_at TIMESTAMPTZ,
    failure_reason TEXT
);

CREATE TABLE IF NOT EXISTS inbox (
    event_id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    state TEXT NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,
    attempts INTEGER DEFAULT 0,
    request_hash TEXT,
    payload_json JSONB,
    last_error TEXT
);

CREATE TABLE IF NOT EXISTS recovery_checkpoints (
    checkpoint_id TEXT PRIMARY KEY,
    cursor_seq BIGINT NOT NULL,
    payload_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS projections (
    name TEXT PRIMARY KEY,
    last_event_seq BIGINT NOT NULL,
    payload_json JSONB NOT NULL,
    rebuilt_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS recon_records (
    recon_id TEXT PRIMARY KEY,
    local_ref TEXT NOT NULL,
    venue_ref TEXT,
    state TEXT NOT NULL,
    detail_json JSONB NOT NULL,
    committed_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
    audit_id TEXT PRIMARY KEY,
    actor TEXT NOT NULL,
    action TEXT NOT NULL,
    target TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS integrity_log (
    check_id TEXT PRIMARY KEY,
    state TEXT NOT NULL,
    detail_json JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS repair_log (
    repair_id TEXT PRIMARY KEY,
    check_id TEXT,
    action TEXT NOT NULL,
    new_event_id TEXT,
    detail_json JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS snapshots (
    snapshot_id TEXT PRIMARY KEY,
    scope TEXT NOT NULL,
    checksum TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS backup_manifest (
    backup_id TEXT PRIMARY KEY,
    path TEXT NOT NULL,
    checksum TEXT NOT NULL,
    event_count INTEGER NOT NULL,
    verified INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS export_packages (
    export_id TEXT PRIMARY KEY,
    checksum TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
"""

SCHEMA_PG_V2 = r"""
CREATE TABLE IF NOT EXISTS backup_schedules (
    schedule_id TEXT PRIMARY KEY,
    cadence_seconds INTEGER NOT NULL,
    retain_count INTEGER NOT NULL,
    last_run_at TIMESTAMPTZ,
    enabled INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS restore_verifications (
    verification_id TEXT PRIMARY KEY,
    backup_id TEXT NOT NULL,
    checksum_ok INTEGER NOT NULL,
    event_count INTEGER NOT NULL,
    verified_at TIMESTAMPTZ NOT NULL,
    detail_json JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS restart_drills (
    drill_id TEXT PRIMARY KEY,
    passed INTEGER NOT NULL,
    log_json JSONB NOT NULL,
    ran_at TIMESTAMPTZ NOT NULL
);
"""

SCHEMA_PG_V2_DOWN = r"""
DROP TABLE IF EXISTS restart_drills;
DROP TABLE IF EXISTS restore_verifications;
DROP TABLE IF EXISTS backup_schedules;
"""

SCHEMA_PG_V3 = r"""
CREATE TABLE IF NOT EXISTS named_projection_meta (
    name TEXT PRIMARY KEY,
    version INTEGER NOT NULL,
    last_event_seq BIGINT NOT NULL,
    rebuilt_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL,
    lag_seq BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS named_projection_rows (
    projection TEXT NOT NULL,
    row_key TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    source_seq BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (projection, row_key)
);
CREATE TABLE IF NOT EXISTS processed_events (
    projection_name TEXT NOT NULL,
    event_id TEXT NOT NULL,
    source_seq BIGINT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (projection_name, event_id)
);
CREATE TABLE IF NOT EXISTS reconciliation_runs (
    run_id TEXT PRIMARY KEY,
    state TEXT NOT NULL,
    venue_available INTEGER NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    closed_at TIMESTAMPTZ,
    payload_json JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS reconciliation_items (
    item_id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    local_ref TEXT NOT NULL,
    venue_ref TEXT,
    classification TEXT NOT NULL,
    severity TEXT NOT NULL,
    state TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (run_id) REFERENCES reconciliation_runs(run_id)
);
CREATE TABLE IF NOT EXISTS mismatch_actions (
    action_id TEXT PRIMARY KEY,
    item_id TEXT NOT NULL,
    run_id TEXT NOT NULL,
    action TEXT NOT NULL,
    actor TEXT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    payload_json JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS restore_applies (
    apply_id TEXT PRIMARY KEY,
    backup_id TEXT NOT NULL,
    target_path TEXT NOT NULL,
    stage TEXT NOT NULL,
    checksum_ok INTEGER NOT NULL,
    schema_ok INTEGER NOT NULL,
    mutated INTEGER NOT NULL,
    trading_blocked INTEGER NOT NULL,
    detail_json JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS money_records (
    record_id TEXT PRIMARY KEY,
    family TEXT NOT NULL,
    field TEXT NOT NULL,
    amount_canonical NUMERIC(28, 8) NOT NULL,
    scale INTEGER NOT NULL,
    currency TEXT NOT NULL,
    source_event_id TEXT,
    committed_at TIMESTAMPTZ NOT NULL
);
CREATE TABLE IF NOT EXISTS inbox_dead_letters (
    event_id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    attempts INTEGER NOT NULL,
    last_error TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);
"""

SCHEMA_PG_INDEXES = r"""
CREATE INDEX IF NOT EXISTS events_correlation_idx ON events (correlation_id);
CREATE INDEX IF NOT EXISTS events_occurred_idx ON events (occurred_at);
CREATE INDEX IF NOT EXISTS events_family_seq_idx ON events (family, sequence_no);
CREATE INDEX IF NOT EXISTS events_idempotency_idx ON events (idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS idempotency_keys_unique_idx ON idempotency_keys (edge, scope, key);
CREATE INDEX IF NOT EXISTS outbox_state_created_idx ON outbox (state, created_at);
CREATE INDEX IF NOT EXISTS outbox_claim_idx ON outbox (state, claimed_until, next_attempt_at);
CREATE INDEX IF NOT EXISTS inbox_state_idx ON inbox (state);
CREATE INDEX IF NOT EXISTS recon_runs_state_idx ON reconciliation_runs (state);
CREATE INDEX IF NOT EXISTS recon_items_run_idx ON reconciliation_items (run_id, severity);
CREATE INDEX IF NOT EXISTS named_proj_source_idx ON named_projection_rows (projection, source_seq);
CREATE INDEX IF NOT EXISTS money_family_idx ON money_records (family, field);
CREATE INDEX IF NOT EXISTS executions_callback_idx ON executions (venue_callback_id);
CREATE INDEX IF NOT EXISTS checkpoints_cursor_idx ON recovery_checkpoints (cursor_seq);
"""

SCHEMA_PG_TRIGGERS = r"""
CREATE OR REPLACE FUNCTION pm8_forbid_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'append-only table % does not allow %', TG_TABLE_NAME, TG_OP
    USING ERRCODE = 'integrity_constraint_violation';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS events_no_update ON events;
CREATE TRIGGER events_no_update BEFORE UPDATE ON events
  FOR EACH ROW EXECUTE FUNCTION pm8_forbid_mutation();
DROP TRIGGER IF EXISTS events_no_delete ON events;
CREATE TRIGGER events_no_delete BEFORE DELETE ON events
  FOR EACH ROW EXECUTE FUNCTION pm8_forbid_mutation();

DROP TRIGGER IF EXISTS audit_log_no_update ON audit_log;
CREATE TRIGGER audit_log_no_update BEFORE UPDATE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION pm8_forbid_mutation();
DROP TRIGGER IF EXISTS audit_log_no_delete ON audit_log;
CREATE TRIGGER audit_log_no_delete BEFORE DELETE ON audit_log
  FOR EACH ROW EXECUTE FUNCTION pm8_forbid_mutation();

DROP TRIGGER IF EXISTS executions_no_update ON executions;
CREATE TRIGGER executions_no_update BEFORE UPDATE ON executions
  FOR EACH ROW EXECUTE FUNCTION pm8_forbid_mutation();
DROP TRIGGER IF EXISTS executions_no_delete ON executions;
CREATE TRIGGER executions_no_delete BEFORE DELETE ON executions
  FOR EACH ROW EXECUTE FUNCTION pm8_forbid_mutation();

DROP TRIGGER IF EXISTS integrity_log_no_update ON integrity_log;
CREATE TRIGGER integrity_log_no_update BEFORE UPDATE ON integrity_log
  FOR EACH ROW EXECUTE FUNCTION pm8_forbid_mutation();
DROP TRIGGER IF EXISTS integrity_log_no_delete ON integrity_log;
CREATE TRIGGER integrity_log_no_delete BEFORE DELETE ON integrity_log
  FOR EACH ROW EXECUTE FUNCTION pm8_forbid_mutation();

DROP TRIGGER IF EXISTS mismatch_actions_no_update ON mismatch_actions;
CREATE TRIGGER mismatch_actions_no_update BEFORE UPDATE ON mismatch_actions
  FOR EACH ROW EXECUTE FUNCTION pm8_forbid_mutation();
DROP TRIGGER IF EXISTS mismatch_actions_no_delete ON mismatch_actions;
CREATE TRIGGER mismatch_actions_no_delete BEFORE DELETE ON mismatch_actions
  FOR EACH ROW EXECUTE FUNCTION pm8_forbid_mutation();

DROP TRIGGER IF EXISTS money_records_no_update ON money_records;
CREATE TRIGGER money_records_no_update BEFORE UPDATE ON money_records
  FOR EACH ROW EXECUTE FUNCTION pm8_forbid_mutation();
DROP TRIGGER IF EXISTS money_records_no_delete ON money_records;
CREATE TRIGGER money_records_no_delete BEFORE DELETE ON money_records
  FOR EACH ROW EXECUTE FUNCTION pm8_forbid_mutation();

DROP TRIGGER IF EXISTS repair_log_no_update ON repair_log;
CREATE TRIGGER repair_log_no_update BEFORE UPDATE ON repair_log
  FOR EACH ROW EXECUTE FUNCTION pm8_forbid_mutation();
DROP TRIGGER IF EXISTS repair_log_no_delete ON repair_log;
CREATE TRIGGER repair_log_no_delete BEFORE DELETE ON repair_log
  FOR EACH ROW EXECUTE FUNCTION pm8_forbid_mutation();
"""

# Ownership / mutability catalog consumed by docs and tests. Not a second schema.
TABLE_FAMILIES: dict[str, dict[str, str]] = {
    "events": {
        "family": "EVENT",
        "authoritative": "yes",
        "mutability": "append-only",
        "pk": "sequence_no",
        "unique": "event_id",
        "idempotency": "event_id / idempotency_key",
        "partitioning": "RANGE(occurred_at) when volume warrants",
    },
    "signals": {
        "family": "SIGNAL",
        "authoritative": "yes",
        "mutability": "insert",
        "pk": "signal_id",
        "unique": "signal_id",
        "idempotency": "via events + REQUEST edge",
        "partitioning": "none (low volume)",
    },
    "orders": {
        "family": "ORDER",
        "authoritative": "yes (local OMS)",
        "mutability": "insert; state via compensating events",
        "pk": "order_id",
        "unique": "client_order_id",
        "idempotency": "client_order_id",
        "partitioning": "none",
    },
    "executions": {
        "family": "EXECUTION",
        "authoritative": "yes (simulated venue only)",
        "mutability": "append-only",
        "pk": "execution_id",
        "unique": "venue_callback_id (nullable)",
        "idempotency": "venue_callback_id",
        "partitioning": "RANGE(committed_at) later",
    },
    "idempotency_keys": {
        "family": "RELIABILITY",
        "authoritative": "yes",
        "mutability": "insert-if-absent",
        "pk": "(edge, scope, key)",
        "unique": "(edge, scope, key)",
        "idempotency": "self",
        "partitioning": "none",
    },
    "outbox": {
        "family": "RELIABILITY",
        "authoritative": "yes",
        "mutability": "state machine (pending/claimed/published/failed/dead-letter)",
        "pk": "outbox_id",
        "unique": "outbox_id",
        "idempotency": "event_id + outbox_id",
        "partitioning": "RANGE(created_at) for history",
    },
    "inbox": {
        "family": "RELIABILITY",
        "authoritative": "yes",
        "mutability": "received → processed | failed | dead-letter",
        "pk": "event_id",
        "unique": "event_id",
        "idempotency": "event_id",
        "partitioning": "none",
    },
    "money_records": {
        "family": "AUDIT",
        "authoritative": "yes",
        "mutability": "append-only",
        "pk": "record_id",
        "unique": "record_id",
        "idempotency": "source_event_id + field",
        "partitioning": "RANGE(committed_at)",
    },
    "reconciliation_runs": {
        "family": "RECONCILIATION",
        "authoritative": "yes",
        "mutability": "state machine",
        "pk": "run_id",
        "unique": "run_id",
        "idempotency": "run_id",
        "partitioning": "none",
    },
    "named_projection_rows": {
        "family": "PROJECTION",
        "authoritative": "no (read model)",
        "mutability": "rebuildable upsert",
        "pk": "(projection, row_key)",
        "unique": "(projection, row_key)",
        "idempotency": "processed_events",
        "partitioning": "none",
    },
    "audit_log": {
        "family": "AUDIT",
        "authoritative": "yes",
        "mutability": "append-only",
        "pk": "audit_id",
        "unique": "audit_id",
        "idempotency": "audit_id",
        "partitioning": "RANGE(occurred_at)",
    },
    "recovery_checkpoints": {
        "family": "RECOVERY",
        "authoritative": "yes",
        "mutability": "insert; cursor_seq monotonic",
        "pk": "checkpoint_id",
        "unique": "checkpoint_id",
        "idempotency": "checkpoint_id",
        "partitioning": "none",
    },
}


def split_sql(script: str) -> list[str]:
    out: list[str] = []
    buf: list[str] = []
    dollar = False
    for line in script.splitlines():
        if "$$" in line:
            dollar = dollar if (line.count("$$") % 2 == 0) else (not dollar)
        buf.append(line)
        if not dollar and line.strip().endswith(";"):
            stmt = "\n".join(buf).strip()
            buf = []
            if stmt:
                out.append(stmt)
    tail = "\n".join(buf).strip()
    if tail:
        out.append(tail)
    return out
