"""Forty independent capital-gate checks. Names are stable for replay."""

CHECK_CATALOG: tuple[str, ...] = (
    "input_schema",
    "idempotency",
    "market_freshness",
    "account_freshness",
    "portfolio_freshness",
    "session_eligibility",
    "regime_eligibility",
    "symbol_eligibility",
    "strategy_profile_eligibility",
    "model_availability",
    "model_freshness",
    "model_quality",
    "model_uncertainty",
    "spread_limit",
    "slippage_limit",
    "commission_cost_limit",
    "stop_loss_existence",
    "stop_loss_distance",
    "min_reward_risk",
    "position_size_validity",
    "max_single_trade_risk",
    "daily_loss_limit",
    "equity_drawdown_limit",
    "consecutive_loss",
    "portfolio_heat",
    "symbol_exposure",
    "currency_exposure",
    "directional_exposure",
    "correlation_concentration",
    "strategy_concentration",
    "profile_allocation",
    "open_order_exposure",
    "pending_order_exposure",
    "duplicate_position",
    "cooldown",
    "max_simultaneous_positions",
    "reconciliation_status",
    "persistence_availability",
    "system_control_state",
    "global_safe_halt",
)

assert len(CHECK_CATALOG) == 40
