from __future__ import annotations

from typing import Protocol

from botmoduleproject1.contracts.v1.execution import NormalizedExecutionCommand


class BrokerAdapter(Protocol):
    name: str

    def available(self) -> bool: ...

    def submit(self, command: NormalizedExecutionCommand, *, now) -> list: ...

    def cancel(self, command: NormalizedExecutionCommand, *, now) -> list: ...

    def modify(self, command: NormalizedExecutionCommand, *, now) -> list: ...

    def close(self, command: NormalizedExecutionCommand, *, now) -> list: ...

    def fetch_open_orders(self) -> tuple: ...

    def fetch_positions(self) -> tuple: ...

    def health(self) -> dict: ...
